### ISSUE TITLE
It's having encoding difficulties

### ISSUE THREAD

**Issue by KristjanLuik** [wunderkraut/wundertools-image-fuzzy-developershell#7]
![image](https://cloud.githubusercontent.com/assets/2822966/15140571/67c68c48-16a4-11e6-991d-caa0355aaa43.png)

**Comment by james-nesbitt** [comment]
can you tell us what encoding your host is using:

```
$/> export | grep LANG
```

We may need some more shell environment variables if that doesn't solve it.

**Comment by james-nesbitt** [comment]
@KristjanLuik  ping ^^

**Comment by KristjanLuik** [comment]
LANG shows this:
`declare -x GDM_LANG="en_US.UTF-8"
declare -x LANG="en_US.UTF-8"
`

**Comment by aleksijohansson** [comment]
I can confirm this issue on OS X and on Arch Linux.

**Comment by james-nesbitt** [comment]
PR 12 has likely fixed this issue by changing the zsh theme back to robbyrussel.

We may try out a new theme in the future.

**Comment by james-nesbitt** [comment]
let's look at this again

**Comment by aleksijohansson** [comment]
It seems that this issue is on the host terminal emulator and I think we don't want to make patching or changing the host machine font as a dependency for this image, but we could add instructions on how to use your own .zshrc file so you can use fancier themes like [Powerline](https://github.com/jeremyFreeAgent/oh-my-zsh-powerline-theme) if you already have a compatible font on the host and want to use it. Closing this one and adding a new issue for the documentation update.
